In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
apartment = np.array([59.5, 31.4, 19, 22, 60550, 2])
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0,1])
apartment = np.append(apartment, share_living_space)


In [6]:
apartment.shape

(5,)

In [13]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
for i, j in enumerate(t):
    print(i+1, j)

t.min()

1 12
2 14
3 17
4 19
5 24
6 28
7 31
8 31
9 27
10 22
11 17
12 13


12

In [20]:
x = np.array([1, 2, math.sqrt(3)])
y = np.array([-1,-2,0])
x+y

array([0.        , 0.        , 1.73205081])

In [22]:
x = np.array([120, 150,90])
y = np.array([130, 130, 130])
z= 72 * np.array([2, 3, 2.5])
print(z, x+y+z)

[144. 216. 180.] [394. 496. 400.]


In [24]:
400*np.array([1, 5, 3, 6]) - 200*np.array([3, 4, 5, 9])


array([-200, 1200,  200,  600])

In [26]:
math.sqrt(53)

7.280109889280518

In [4]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5,12,10,3,6,13,8,21,5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [39]:
hutp = Hut_Paradise_DF.values
hutp

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

In [49]:
hutp[:,3][2]

10

In [42]:
hutp[:,3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [52]:
len(hutp)

9

In [53]:
hutp[:, 1] - hutp[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [55]:
hutp[:,0] *0.4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [57]:
array = np.arrange([])

27.2

In [2]:
14*np.array([10,20,30,15,5,40,20,8,20])

array([140, 280, 420, 210,  70, 560, 280, 112, 280])

In [7]:
time=np.array([10,20,30,15,5,40,20,8,20])

np.dot(Hut_Paradise_DF.iloc[:,4], time)

1348

In [8]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [12]:
new = 2*v-3*w
np.dot(new, u)

0

In [14]:
u_norm =  u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)

print(u_norm, v_norm, w_norm)

[0.8660254  0.         0.28867513 0.28867513 0.28867513] [ 0.          0.33333333  0.          0.66666667 -0.66666667] [ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]


In [15]:
A = np.matrix("1, -5; 2, 2; 0, 3")

In [17]:
A.T

matrix([[ 1,  2,  0],
        [-5,  2,  3]])

In [18]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [33]:
inc = np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [34]:
cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption]).T
cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [36]:
new_inc = inc*0.87

In [38]:
P = new_inc - cons
P


array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [40]:
X = np.matrix("1,1;2,-1;1,2")
X@X.T

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])

In [48]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A.shape

(2, 5)

In [50]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
print(A.shape, B.shape)
B@A

(5, 4) (2, 5)


array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [61]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
A = np.array([x, y, z])
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [85]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [86]:
count = Count_DF.values
price = Price_DF.values
print(count,  price)

[[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]] [[2.  1.5 1.  0.8 1. ]
 [1.8 2.5 1.  1.  1. ]
 [2.  2.  0.  0.5 2. ]
 [1.8 1.2 2.8 0.8 2. ]
 [2.5 3.5 2.  1.  1.5]
 [5.  5.  3.  2.  2.5]
 [1.1 1.  1.5 0.5 1.7]
 [4.5 4.  2.5 1.  2. ]]


In [87]:
price[1]*count[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [88]:
com = [0.2, 0.2, 0.3, 0.1, 0.1]
inc_all = (price*count)@com

In [89]:
style_inc = (price*count)@(np.ones(5)-com)

In [90]:
style_inc

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [91]:
A = np.matrix("1,2,3;4,5,6;7,8,10")
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [97]:
A = np.matrix("2,0,0; 0,1,0; 0,0,4")
np.linalg.det(A2)

0.12500000000000003

In [96]:
A2=np.linalg.inv(A)

In [98]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [99]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])
A = np.array([v1,v2,v3,v4])

In [100]:
np.linalg.matrix_rank(A)

4

In [104]:
B=A@A.T

In [107]:
np.linalg.inv(B)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])