In [1]:
import numpy as np
import pandas as pd
# !pip3 install pandas

In [6]:
arr1 = np.array([1, 2 ,3])
arr1

array([1, 2, 3])

In [10]:
arr2 = np.array([[[1, 
                   2,
                   5]]], dtype=float)
arr2

array([[[1., 2., 5.]]])

In [15]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr3.shape

(3, 3)

In [17]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [18]:
mys = pd.Series([5,6,7,8,9,10])
mys.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [34]:
np.empty(5)
np.zeros((10,7))
np.ones((3,3,3))
np.eye(3)
np.full((3,3), 3.149)
np.arange(0,21,7)
np.linspace(0,1,5)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
my_array = np.array([x for x in range(10)])
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [17]:
my_array = np.array([[1,2,3,4], [10, 11, 12, 13], [45, 46, 47, 48]])
my_array
my_array[1][2]
my_array[1, 2]

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48]])

In [12]:
first_line = [x*y for x in range(2, 100, 6) for y in range(7, 1, -2)]
second_line = [x**0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line]) 
# big_secret

In [13]:
sum = 0
for line in big_secret:
    sum += line[-1]
sum

3154.332495807108

In [14]:
new_secret = np.zeros((5,5))
for i in range(len(big_secret)):
    new_secret[i] = big_secret[i][:5]
#     print(line)
# big_secret[0][:5]
new_secret
diag_sum = np.diag(new_secret)
diag_sum.sum()


121.37188663699624

In [15]:
big_secret = np.array([first_line, second_line, third_line, second_line, first_line]) 
new_secret = np.zeros((5,5))
for i in range(len(big_secret)):
    new_secret[i] = big_secret[i][-5:]
new_secret
diag_sum = np.diag(new_secret)
diag_sum.prod()

341505315559.2347

In [10]:
my_array = np.random.randint(1, 100, (4, 6))
my_slice = my_array[1:3, 2:4]
my_slice[:] = 0
my_array
# big_secret

array([[ 1, 60, 60, 54,  4, 67],
       [43, 72,  0,  0, 96, 81],
       [ 9, 97,  0,  0,  9, 84],
       [41, 10, 65, 28, 82, 20]])

In [16]:
big_secret = np.array([first_line, second_line, third_line, second_line, first_line]) 
my_slice = big_secret[0::2, 0::2]
my_slice[:] = -1
my_slice2 = big_secret[1::2, 1::2]
my_slice2[:] = 1
# big_secret

In [142]:
slicee = big_secret[:, -5:]
sumd = np.diag(slicee).sum()
prod = np.diag(slicee).prod()
prod

-1.0

In [11]:
a = np.array([3, 6, 9])
b = np.array([12, 15, 18])

result1 = a+b
result2 = b - a 
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1,
                                                                                                      result2,
                                                                                                      result3, 
                                                                                                      result4, 
                                                                                                      result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [13]:
my_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [15]:
my_array = np.random.randint(0, 10, 20)
my_array
my_array.reshape((4, 5))

array([[2, 1, 8, 6, 1],
       [3, 3, 4, 3, 4],
       [5, 2, 9, 8, 4],
       [6, 1, 8, 9, 0]])

In [17]:
my_array = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
my_array
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [2]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array[1:4, 1:4]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [49]:
np.sum(np.sin(my_array))

-0.05812430261413351

In [3]:
my_sin = np.sin(my_array)
my_sin
new_arr = my_sin[1:4, 1:4]
new_arr[:] = 1
my_sin
# np.sum(my_sin)
# np.sum(np.sin(my_array))

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [16]:
np.sum(my_sin[:, :4].reshape((10, 2))[:, 0])

2.4057172058139544

In [13]:
bigdata = np.array([x**2 for x in range(100,1000) if x%2 != 0])
# bigdata

In [12]:
np.median(bigdata)

302501.0

In [15]:
np.std(bigdata)

292095.0301991155

In [18]:
np.corrcoef(bigdata[0::2], bigdata[1::2])

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])